language: python

sudo: false

env:
    - TOX_ENV=py34-django17
    - TOX_ENV=py33-django17
    - TOX_ENV=py32-django17
    - TOX_ENV=py27-django17
    - TOX_ENV=py34-django18rc
    - TOX_ENV=py33-django18rc
    - TOX_ENV=py32-django18rc
    - TOX_ENV=py27-django18rc

install:
    - pip install tox

script:
    - tox -e $TOX_ENV