language: python

sudo: false

env:
    - TOX_ENV=py34-django17
    - TOX_ENV=py33-django17
    - TOX_ENV=py32-django17
    - TOX_ENV=py27-django17
    - TOX_ENV=py34-django18beta
    - TOX_ENV=py33-django18beta
    - TOX_ENV=py32-django18beta
    - TOX_ENV=py27-django18beta

install:
    - pip install tox

script:
    - tox -e $TOX_ENV