language: python

python:
    - "2.7"
    - "3.6"

sudo: false

env:
    - TOX_ENV=py36-django111
    - TOX_ENV=py27-django111
    - TOX_ENV=py36-django20

install:
    - pip install tox

script:
    - tox -e $TOX_ENV
